### ISSUE TITLE
Install vim :)

### ISSUE THREAD

**Issue by omar-moreno** [tomeichlersmith/hps-env#10]

**Comment by tomeichlersmith** [comment]
We already chatted on slack, but I'm going to write up a more detailed response here for future readers.

I don't want to install `vim` or any user-specific things since that would then open the door to trying to accommodate everyone's workflow and eventually bloat the image. There are two ways around this (both of which I use).

## 1. password-less sudo
If you are using `distrobox` with podman or docker, then you will have passord-less sudo access within the container and can install whatever additional packages you want. If you find yourself reinstalling the same packages again and again, you can do it once and then "commit" the changes to the container to a new image. ([docker commit](https://docs.docker.com/engine/reference/commandline/commit/) [podman commit](https://docs.podman.io/en/latest/markdown/podman-commit.1.html)). Rough sketch:
```
distrobox create -i tomeichlersmith/hps-env:latest -n hps-env -H /path/to/hps
distrobox enter hps-env
# install what you like
# leave
exit
docker/podman commit hps-env my-hps-env
# use docker/podman image ls to make sure my-hps-env is there
distrobox rm -f hps-env
distrobox create -i my-hps-env -n hps-env -H /path/to/hps
```
Then this process would only need to be re-done whenever you want to update the underlying hps-env container.

## 2. Side-by-Side
I find myself usually running code in one terminal (or tmux pane) and then viewing the code in a second terminal (tmux pane) in a kind of "split screen" view. In this case, you would obviously have the side for running the code be in the container environment with all the dependencies and the other view can be whatever your favorite way of viewing the code is.
